version: '3.3'
services:
  mysqldb:
    image: mysql/mysql-server
    container_name: mysql-compose
    ports: 
      - 3306:3306
    environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: library
  tomcat:
    image: rvfedorin/tomcat9-with-users
    container_name: tomcat-compose
    ports:
      - 8080:8080
    links:
      - mysqldb
